### ISSUE TITLE
未找到 Taro.Component 的类定义

### ISSUE THREAD

**Issue by gdpu-wxq** [NervJS/taro-v2ex-hooks#1]
各种未找到 Taro.Component 的类定义,请问怎么解决

**Comment by crossjs** [comment]
请问是怎么解决的？

**Comment by xuedingesmiao** [comment]
同问如何解决

**Comment by crossjs** [comment]
我这边的问题是，全局的 taro 与本地的版本不一致（全局太旧了），更新后就解决了。

不过页面还是不能使用 functional component，只有非页面的组件可用。

**Comment by gdpu-wxq** [comment]
> 我这边的问题是，全局的 taro 与本地的版本不一致（全局太旧了），更新后就解决了。
> 
> 不过页面还是不能使用 functional component，只有非页面的组件可用。



> 同问如何解决

忘记了...估计就是版本的原因吧
